####################################################################################
# docker-compose file for Apache Guacamole
# created by PCFreak 2017-06-28
#
# Forked and edited for use with MariaDB by Grevlingkroken 2023-10-28

version: '2.0'

# networks
# create a network 'guacnet' in mode 'bridged'
networks:
  guacnet:
    driver: bridge

# services
services:
  # guacd
  guacd:
    container_name: guacd
    image: guacamole/guacd
    networks:
      guacnet:
    restart: always
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw
  # MariaDB
  mariadb:
    container_name: mariadb_guacamole
    image: mariadb:10.11.5
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: guacamole_db
      MYSQL_PASSWORD: ${GUACAMOLE_PASSWORD}
      MYSQL_USER: guacamole_user
    networks:
      guacnet:
    restart: always
    volumes:
    - ./init:/docker-entrypoint-initdb.d:z
    - ./data:/var/lib/mysql/:rw

  # guacamole
  guacamole:
    container_name: guacamole
    depends_on:
    - guacd
    - mariadb
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_DATABASE: guacamole_db
      MYSQL_HOSTNAME: mariadb
      MYSQL_PASSWORD: ${GUACAMOLE_PASSWORD}
      MYSQL_USER: guacamole_user
      # TOTP_ENABLED: "true" Enable this when you know the install is working
    image: guacamole/guacamole
    links:
    - guacd
    networks:
      guacnet:
    ports:
## enable next line if not using nginx
##    - 8080:8080/tcp # Guacamole is on :8080/guacamole, not /.
## enable next line when using nginx
    - 8080/tcp
    restart: always

########### optional ##############
  # nginx
  nginx:
   container_name: nginx_guacamole
   restart: always
   image: nginx
   volumes:
   - ./nginx/templates:/etc/nginx/templates:ro
   - ./nginx/ssl/self.cert:/etc/nginx/ssl/self.cert:ro
   - ./nginx/ssl/self-ssl.key:/etc/nginx/ssl/self-ssl.key:ro
   ports:
   - 8443:443
   links:
   - guacamole
   networks:
     guacnet:
####################################################################################
